### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Lua-kr** [waffle-lord/aoc2023#1]
I have an issue that I want waffles.

**Comment by waffle-lord** [comment]
🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 🧇 

This should suffice

**Comment by Lua-kr** [comment]
I want round waffles, not that kind of waffles.
Also I want Icecream on it.
